create database customer_shopping_behavior;

use customer_shopping_behavior;

select * from customer_shopping;

-- Q1 - What is the total revenue generated by Male vs Female customers
SELECT Gender, SUM(purchase_amount) as Revenue
FROM customer_shopping
GROUP BY Gender ORDER BY Revenue DESC;

-- Q2 -  Which customers used a discount but still spent more than the average purchase amount.
SELECT customer_id, purchase_amount, discount_applied
FROM customer_shopping
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
      SELECT AVG(purchase_amount)
      FROM customer_shopping
  );
  
  -- Q3 - Which are the top 5 products having highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating), 2) as average_review_rating
FROM customer_shopping 
GROUP BY item_purchased
ORDER BY ROUND(AVG(review_rating), 2) DESC LIMIT 5;

-- Q4 - Compare the average purchase amounts between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) as average_purchase_amount
from customer_shopping
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5 - Do subscribe customer spend more? Compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status,
	   COUNT(customer_id) as total_customers,
	   ROUND(AVG(purchase_amount), 2) as average_spend, 
       SUM(purchase_amount) as total_revenue
from customer_shopping
GROUP BY subscription_status;

select * from customer_shopping;

-- Q6 - Which 5 products have highest percentage of purchase with discounts applied?
SELECT item_purchased,
       ROUND(
         SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
       2) AS discount_rate
FROM customer_shopping
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
	
-- Q7 - Segement customers into new, returning, and loyal based on their total no. of previous purchase and show the count of each segment
WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
END AS customer_segment
FROM customer_shopping)

SELECT customer_segment,
       COUNT(*) AS customer_count
FROM customer_type
GROUP BY customer_segment;

-- Q8 - What are the top 3 purchased products within each category
-- SELECT item_purchased, 
--        category,
--        SUM(purchase_amount) as amount
-- FROM customer_shopping
-- GROUP BY item_purchased, category 
-- ORDER BY category, amount DESC
-- LIMIT 3;

WITH item_count as (
SELECT category, 
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over (PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer_shopping 
GROUP BY category, item_purchased 
)

SELECT item_rank, category, item_purchased, total_orders
from item_count
WHERE item_rank <=3;


-- Q9 - Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(*) as Subscriber_count
FROM customer_shopping
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY subscriber_count DESC;

-- Q10 - What is the revenue contribution of each age group
SELECT age_group,
       SUM(purchase_amount) as revenue
FROM customer_shopping 
GROUP BY age_group
ORDER BY revenue DESC;